### PR TITLE
Change flowchart color

### PR DESCRIPTION
**Pull request by hendricius**
This adds a couple of small design changes to the flow charts.

image

### CODE REVIEW

**Comment by cedounet** [comment]
I wasn't brave enough to change the blue to white LoL

**Comment by cedounet** [comment]
Looks like i can't push to your branch... any way you would  allow that ?  A very minor tweak

**Comment by hendricius** [comment]
@cedounet I am not 100% sure, I made you a collaborator now. Is it not possible to allow others to push to a pull request directly? 🤔 I searched a bit and couldn't find an answer.

**Comment by cedounet** [comment]
Works now... So excited I was to try i did not test locally first...

Went a little further than I thought, and re-enabled support for standalone flowcharts png generation.  Works on my debian machine but the binary is not called imagemagick.

C

**Comment by cedounet** [comment]
@hendricius note I can now merge PR into main... I will not do it (at least on purpose), but if you are note comfy with that I would not be offended.

**Comment by hendricius** [comment]
@cedounet no worries. Feel free to do so 🙇

**Comment by cedounet** [comment]
I would need to merge main but otherwise I can actually push now.

**Pull request merged**
