### PR TITLE
Small changes to Docker command and `.gitignore`

### PR DESCRIPTION
**Pull request by sha1sum**
- Adds `.DS_Store` to `.gitignore` for Mac users.
- Adds `--rm` option flag to `docker` command so that containers are removed when the process is finished rather than leaving a bunch of containers around.

### CODE REVIEW

**Comment by cedounet** [comment]
Can you please check why CI failed.

thanks.

**Comment by sha1sum** [comment]
@cedounet I can only assume it's something to do with permissions. It's getting a 403 forbidden when trying to upload something.

**Comment by sha1sum** [comment]
This is coming from my fork so I'm not sure that the Docker image will push because it's not running with the GitHub Actions token from this repo I don't think.

**Comment by cedounet** [comment]
Yeah that makes sense.  I will let @hendricius to merge, but +1 from me.

**Review by hendricius — APPROVED** [review]

**Pull request merged**
