### PR TITLE
Use input figs

### PR DESCRIPTION
**Pull request by cedounet**
Address both:

- https://github.com/hendricius/the-sourdough-framework/issues/119
- https://github.com/hendricius/the-sourdough-framework/issues/115

I am tempted to think all the ebooks-makefile issues were related, svg looks fine as far as I can tell.
Some other little changes like centering the pics.

### CODE REVIEW

**Comment by hendricius** [comment]
Thanks! So I took a couple of screenshots. It seems that the tables work fine, but the SVGs for the flowcharts don't. That was the reason why I back then moved them to another file.

Apple Books:
image

Calibre:
image

In Calibre ebook viewer you can activate the debugger and then inspect the HTML. Quite useful to find out what might be wrong. It's using chrome internally as the viewer.

How do you best suggest we proceed here?

**Comment by cedounet** [comment]
Thanks! Now that I have an example I can actually try to see if I see the problem myself.  I keep you posted.

**Comment by cedounet** [comment]
It works for me (R) (C) (TM).  

Is that the one locally built or the one built on the server you are showing here?  Both apple ebook and calibre are very happy with the document:
Screenshot 2023-06-17 at 08 14 08

**Comment by cedounet** [comment]
Versions of tools I use (github action uses more recent versions)

latexmk --version
Latexmk, John Collins, 7 Jan. 2023. Version 4.79

pdflatex --version
pdfTeX 3.141592653-2.6-1.40.25 (TeX Live 2023)
kpathsea version 6.3.5
Compiled with libpng 1.6.39; using libpng 1.6.39
Compiled with zlib 1.2.13; using zlib 1.2.13
Compiled with xpdf version 4.04

tex4ebook --version
tex4ebook v0.3i

make4ht --version
make4ht version v0.3m

kindlegen --version

*************************************************************
 Amazon kindlegen(MAC OSX) V2.9 build 0000-kdevbld 
 A command line e-book compiler 
 Copyright Amazon.com and its Affiliates 2015 
*************************************************************

Error(kindlegen):E30010: Unsupported argument  --version

**Comment by hendricius** [comment]
@cedounet can you run `make bake` in the root folder of the repo? This should start to compile everything inside of a docker image.

I am getting the following error:

```
1 of 33 pages converted in 2.33453 seconds
HTML Tidy for Linux version 5.8.0
...dir/texmf-dist/scripts/tex4ebook/tex4ebook-exec_epub.lua:295: signal
make: *** [makefile:48: epub/book.epub] Error 1
make: *** [bake] Error 2
```

**Comment by hendricius** [comment]
```
calibre --version
calibre (calibre 6.21)
```

image

Very very strange! Could you send me the .epub you generate please? Maybe dropbox/drive/wetransfer. I'd love to open your epub and check if I have the same issue.

**Comment by cedric-andrieu** [comment]
❯ calibre --version
calibre (calibre 6.21)

I don't have docker, but I will find a way to send you the locally built version.

**Comment by cedounet** [comment]
❯ calibre --version
calibre (calibre 6.21)

I don't have docker, but I will find a way to send you the locally built version.

**Comment by cedounet** [comment]
https://www.transfernow.net/dl/20230626zkhQmaWx/BxV7uXBp has pdf and epub.  Built locally on the mac w/o Docker.

**Comment by hendricius** [comment]
Thanks.

image

Looks wonderful with your version 🙈. Dafuq - we have the same versions? What's your OS version and language? OS X `13.3.1 (a) (22E772610a)`

**Comment by cedounet** [comment]
System  : MacOS Darwin
Kernel  : Darwin 22.5.0
Date    : 2023-06-27 09:31:26
Shell   : Zsh 5.9 (PID = 50534, 1 nests)
Term    : /dev/ttys000 (xterm-256color),  bauds, 143 x 40 cars
Locale  : en_GB.UTF-8
Uptime  :  09:31:26  up 1 day  0:29,  3 users,  load average: 1.41, 1.77, 2.78

❯ uname -a
Darwin 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64 x86_64 i386 Darwin

**Comment by cedounet** [comment]
FWIW it does not build on my debian machine(s) Still need to raise a bug for that.  Does not build _before_ those changes, not a regression.

**Comment by hendricius** [comment]
> FWIW it does not build on my debian machine(s) Still need to raise a bug for that. Does not build _before_ those changes, not a regression.

Yep. This recent commit might have fixed it: https://github.com/michal-h21/tex4ebook/commit/19b8e7dad32209158012eab002530705da07b655. I am currently testing it and will keep you posted.

Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64

**Comment by hendricius** [comment]
I am merging this for now, it seems to be a problem on my computer. Thank you very much!

**Comment by cedounet** [comment]
The export_figures still needs some love though.  I am happy to help but I do not have dockers, let me know how i can help you @hendricius

**Comment by hendricius** [comment]
@cedounet we'd just somehow need to move the flowchart svgs into a new folder with a command. I don't think we need docker anymore because we have SVGs. I used it in the past to resize the pngs without having to install the whole imagemagick suite locally.

**Comment by hendricius** [comment]
> The export_figures still needs some love though. I am happy to help but I do not have dockers, let me know how i can help you @hendricius

I see this still works! Let me publish a PR

**Pull request merged**
