### PR TITLE
Nicer/Simpler tables

### PR DESCRIPTION
**Pull request by cedounet**
It does simplify the code a lot, but there might have been a reason they were built separately and added as image...  Let me know if you like it or not.

### CODE REVIEW

**Comment by hendricius** [comment]
Thanks a lot! I note you put a `TODO` in there, but let's merge it for now to avoid conflicts.

I originally included the tables like this to solve #59 but it seems that your way of including them also solves the issue.

**Comment by hendricius** [comment]
@cedounet I noticed some small issues with the new tables when gerating the .epub version. Details here: https://www.loom.com/share/45e87cbb38304285aa91992e0682de8a

**Comment by hendricius** [comment]
I have reverted the merge for now. It seems like this somehow breaks the .epub version that is built by the github actions. The version I create locally via OSX works. Revert commit: https://github.com/hendricius/the-sourdough-framework/commit/0d1602cc172fa29de25d537a261baf096171f7a0.

**Comment by cedounet** [comment]
1) I will have a look at the one that look bad, that should be possible to sort them out

2) How can i debug the 2nd one (Github actions?) if it builds for me it... is there a log somewhere.

Thanks

**Comment by cedounet** [comment]
Re: Ch6

I have a fix for that, it now looks fine in ch6.html.  But i have no warning whatsoever. Pdf is not as nice but we can live with that.

Ch9:
- works for me (R)(C)(TM).  No warnings and nice looking html in Firefox.

My env

❯ brew info texlive
==> texlive: stable 20230313 (bottled), HEAD

❯ tex4ebook -c tex4ebook.cfg -f epub book.tex
[STATUS]  tex4ebook: Conversion started
[STATUS]  tex4ebook: Input file: book.tex
HTML Tidy for Mac OS X released on 31 October 2006 - Apple Inc. build 10443
[STATUS]  tex4ebook: Conversion finished

❯ tex4ebook --version
tex4ebook v0.3i

❯ uname -a
Darwin XXX 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64 x86_64 i386 Darwin

**Comment by hendricius** [comment]
Sweet! I have a similar setup. Can you open up the PR again? Then I can test and see if it works locally 👍.

Do you have docker running? Else just open up the PR and we can see the output of the Github actions. I suspect the tidyhtml is a bit different on OS X compared to the linux version.

**Pull request merged**
