### PR TITLE
Add list of table and list of figures

### PR DESCRIPTION
**Pull request by cedounet**
At the end of document for easier navigation.

### CODE REVIEW

**Comment by hendricius** [comment]
Loaf it. 
image

I noticed that here at the end there seems to be some space missing between the number and the figure? Is that something we could fix?

**Comment by hendricius** [comment]
image

Noticed this for the website. But don't worry. I'll fix it after your PR is merged.

**Comment by cedounet** [comment]
you eagle eye.. I will google what the parameter is, drawback is that the space will be too large for small numbers.

On a second thought I will try to split the figures further into listofflowchart and listoffigures.  Those flowchart are probably the one that i am keen to get quick access to.

**Comment by hendricius** [comment]
> you eagle eye.. I will google what the parameter is, drawback is that the space will be too large for small numbers.
> 
> On a second thought I will try to split the figures further into listofflowchart and listoffigures. Those flowchart are probably the one that i am keen to get quick access to.

Loafely idea. Agreed - that would be super useful!

**Comment by hendricius** [comment]
Thank you!

**Pull request merged**
