### PR TITLE
Introduce Lychee

### PR DESCRIPTION
**Pull request by szepeviktor**
Check links in documents.

### CODE REVIEW

**Comment by cedounet** [comment]
What does it do?

**Comment by szepeviktor** [comment]
Starts HTTP requests for all URL-s.
Then fails on non-200 responses.

**Comment by cedounet** [comment]
Cool.  Then it would be better to have it run in main makefile. Not in the upper one.

if it is not packaged in in Debian I am not sure I want it as part of build all though.


Thanks

**Comment by szepeviktor** [comment]
Lychee moves fast. It is a single Rust binary.

**Comment by cedounet** [comment]
Not sure we need to close it.  

I will take it if this is in the right makefile (and not blocking release)

**Pull request closed without merging**
