### PR TITLE
Force flowchart width to 100%

### PR DESCRIPTION
**Pull request by cedounet**
For all floats actually...

@hendricius this is the first css I ever wrote, or even red LoL... could you please have a look.

### CODE REVIEW

**Comment by hendricius** [comment]
@cedounet just for the ebooks right? Or also the website?

**Comment by hendricius** [comment]
And .... congrats for your first CSS. You are now a fullstack developer.

**Comment by cedounet** [comment]
Yeah website seems fine… so I did not touch it.

**Comment by cedounet** [comment]
Also unvealed a bug in the makefile.. Fixed now.

**Pull request merged**
