### PR TITLE
Section on mix-ins

### PR DESCRIPTION
**Pull request by fischerq**
Hi! I started a section on mix-ins (basically: other stuff you may want to put into your bread beyond a plain loaf).
I didn't fully polish this yet, happy to put in a bit more time if you'd like to include it in the book.

### CODE REVIEW

**Comment by hendricius** [comment]
@fischerq loaf the idea! This is really amazing. It will provide a really good basis for people to decide on mixins. I am happy to take some pictures too with my good camera. Any suggestions on what I should prioritize on? Maybe couple of smaller mixins and then some colors?

**Comment by fischerq** [comment]
Yay, glad you like it! Let me clean it up a bit more to get it good enough to merge.

Yeah, I think some picture work really help give the reader a feel for the possible variations. Maybe could put a table with 2-3 pics at the end of each section?
Smaller ones (maybe seeds, sesame and/or pumpkin?) and colors sound great!

**Comment by fischerq** [comment]
@hendricius I've cleaned up, could you take a look whether it is good to merge?

I added comments with link to a reference and to a few particularly nice pictures. Would it make sense to reach out to the people that posted them (most are from /r/sourdough) whether they could be used in the book, or do you want to include only self-taken pictures?

**Comment by hendricius** [comment]
Nice. Thank you! How about we source the pictures in the bread code community? I didn't have time to read through this in detail yet. I'll do so soon (next 3 weeks as I am heading for a bike tour) and then add some more points.

I've posted on our Discord asking for some help.

**Comment by hendricius** [comment]
I will merge it for now and then we can continue with a couple of followup PRs. Hope that's okay. Thank you!

**Pull request merged**
