### PR TITLE
Use trixie as base image

### PR DESCRIPTION
**Pull request by hendricius**
FYI @cedounet 

```
uname -a
Linux d887876c6f8d 6.3.13-linuxkit #1 SMP PREEMPT Thu Sep  7 07:48:47 UTC 2023 x86_64 GNU/Linux

/bin/bash --version
GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

latexmk --version
Latexmk, John Collins, 4 Apr. 2023. Version 4.80

lualatex --version
This is LuaHBTeX, Version 1.17.0 (TeX Live 2023)
Development id: 7581

Execute  'luahbtex --credits'  for credits and version details.

There is NO warranty. Redistribution of this software is covered by
the terms of the GNU General Public License, version 2 or (at your option)
any later version. For more information about these matters, see the file
named COPYING and the LuaTeX source.

LuaTeX is Copyright 2022 Taco Hoekwater and the LuaTeX Team.


tex4ebook --version
tex4ebook v0.3j

make4ht --version
make4ht version v0.3m

tidy -version
HTML Tidy for Linux version 5.6.0

dvisvgm --version
dvisvgm 3.0.3

lacheck --version
LaCheck (TeX Live) 1.30
$Id: lacheck.l 63190 2022-04-30 22:15:57Z karl $
License GPLv1+: GNU GPL version 1 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Kresten Krab Thorup and Per Abrahamsen.

chktex --version
ChkTeX v1.7.8 - Copyright 1995-96 Jens T. Berger Thielemann.
Compiled with POSIX extended regex support.

make --version
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

biber -version
biber version: 2.19

ruby --version
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-gnu]

convert --version
Version: ImageMagick 6.9.12-98 Q16 x86_64 18038 https://legacy.imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP(4.5)
Delegates (built-in): bzlib djvu fftw fontconfig freetype heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png raw tiff webp wmf x xml zlib

rsync --version
rsync  version 3.2.7  protocol version 31
Copyright (C) 1996-2022 by Andrew Tridgell, Wayne Davison, and others.
Web site: https://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, symlinks, symtimes, hardlinks, hardlink-specials,
    hardlink-symlinks, IPv6, atimes, batchfiles, inplace, append, ACLs,
    xattrs, optional secluded-args, iconv, prealloc, stop-at, no crtimes
Optimizations:
    SIMD-roll, no asm-roll, openssl-crypto, no asm-MD5
Checksum list:
    xxh128 xxh3 xxh64 (xxhash) md5 md4 sha1 none
Compress list:
    zstd lz4 zlibx zlib none
Daemon auth list:
    sha512 sha256 sha1 md5 md4

rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.
```

Getting some errors when running `make bake now`:

```
[WARNING] domfilter: DOM parsing of listoflocname.html failed:
[WARNING] domfilter: ...ive/2023/texmf-dist/tex/luatex/luaxml/luaxml-mod-xml.lua:175: Unbalanced Tag (/body) [char=16010]

[WARNING] domfilter: DOM parsing of listoflocname.html failed:
[WARNING] domfilter: ...ive/2023/texmf-dist/tex/luatex/luaxml/luaxml-mod-xml.lua:175: Unbalanced Tag (/body) [char=16010]

[WARNING] domfilter: DOM parsing of listtablename.html failed:
[WARNING] domfilter: ...ive/2023/texmf-dist/tex/luatex/luaxml/luaxml-mod-xml.lua:175: Unbalanced Tag (/body) [char=15649]

[WARNING] domfilter: DOM parsing of listtablename.html failed:
[WARNING] domfilter: ...ive/2023/texmf-dist/tex/luatex/luaxml/luaxml-mod-xml.lua:175: Unbalanced Tag (/body) [char=15649]

[WARNING] domfilter: DOM parsing of listfigurename.html failed:
[WARNING] domfilter: ...ive/2023/texmf-dist/tex/luatex/luaxml/luaxml-mod-xml.lua:175: Unbalanced Tag (/body) [char=22455]

[WARNING] domfilter: DOM parsing of listfigurename.html failed:
[WARNING] domfilter: ...ive/2023/texmf-dist/tex/luatex/luaxml/luaxml-mod-xml.lua:175: Unbalanced Tag (/body) [char=22455]

[WARNING] exec_epub: Missing opf file
...023/texmf-dist/scripts/tex4ebook/tex4ebook-exec_epub.lua:341: attempt to index a nil value (local 'f')
make: *** [makefile:93: epub/book.epub] Error 1
```

### CODE REVIEW

**Comment by cedounet** [comment]
Nice.  Try to enable make DEBUG=1 bake we will see what file is missing or why?

I think i installed dvisvgm manually as well.. at least I have a different version.

Thanks

**Comment by hendricius** [comment]
I'm stupid. Updated  `make show_tools_version`

```
uname -a
Linux 826fbe43c169 6.3.13-linuxkit #1 SMP PREEMPT Thu Sep  7 07:48:47 UTC 2023 aarch64 GNU/Linux

/bin/bash --version
GNU bash, version 5.2.15(1)-release (aarch64-unknown-linux-gnu)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

latexmk --version
Latexmk, John Collins, 4 Apr. 2023. Version 4.80

lualatex --version
This is LuaHBTeX, Version 1.17.0 (TeX Live 2023/Debian)
Development id: 7581

Execute  'luahbtex --credits'  for credits and version details.

There is NO warranty. Redistribution of this software is covered by
the terms of the GNU General Public License, version 2 or (at your option)
any later version. For more information about these matters, see the file
named COPYING and the LuaTeX source.

LuaTeX is Copyright 2022 Taco Hoekwater and the LuaTeX Team.


tex4ebook --version
tex4ebook v0.3j

make4ht --version
make4ht version v0.3m

tidy -version
HTML Tidy for Linux version 5.6.0

dvisvgm --version
dvisvgm 3.1.2

lacheck --version
LaCheck: Could not open : --version

chktex --version
ChkTeX v1.7.8 - Copyright 1995-96 Jens T. Berger Thielemann.
Compiled with PCRE regex support.

make --version
GNU Make 4.3
Built for aarch64-unknown-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

biber -version
biber version: 2.19

ruby --version
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [aarch64-linux-gnu]

convert --version
Version: ImageMagick 6.9.12-98 Q16 aarch64 18038 https://legacy.imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP(4.5)
Delegates (built-in): bzlib djvu fftw fontconfig freetype heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png raw tiff webp wmf x xml zlib

```
And voila - the ebook and the website works again with this fix. Strange that it suddenly stopped working ⭐

**Comment by hendricius** [comment]
As per #282 we probably need to let the build run twice until the ebooks are fixed again. Doing one final test locally here. The docker image now builds slower too since we are manually installing tex, but that should also give us more control over the dependencies.

**Comment by cedounet** [comment]
That is awesome 👏 thanks.

**Pull request merged**
