### PR TITLE
Minor punctuation and grammatical fixes to Preface and History.

### PR DESCRIPTION
**Pull request by hanclintonnyx**
Did a proofreading once-through on Preface and History.  Mainly added needed commas, but also some other minor capitalizations ("world war II" to "World War II"), diacritical marks ("naive" to "naïve") and a few other grammar convention fixes.

### CODE REVIEW

**Comment by hanclintonnyx** [comment]
Also added proofreading for "How Sourdough Works" chapter.

**Comment by hendricius** [comment]
Thank you Han! Great comments and improvements. I saw you changing `dutch oven` to `Dutch oven`. Is that because `Dutch` is a language?

**Comment by stephenulmer** [comment]
That’s because french fries aren’t directly from French the language, but are short for “frenched and fried potatoes”, the “frenched” being the style of the cut. The term “frenching” (as it relates to culinary arts) seems to have lost its capitalization somewhere else… :)

If you want to get completely in the weeds, you can pick a style guide and refer to it:

[What Is a Writing Style Guide, and Which One Should You Use?](https://thewritelife.com/writing-style-guide/)

I learned MLA (at least for citations) in primary and secondary school (in Florida in the US), but various publishing houses pick different ones for their authors based on their target audience. I have no current recommendation, other than maybe use the one that already matches the citations you want to use (or possibly none at all?)

Love the book at YouTube!

**Comment by hanclintonnyx** [comment]
That's true--I forgot that it was because of frenching.  But I don't know why [dutch orange](https://www.merriam-webster.com/dictionary/dutch%20orange) and [dutch pink](https://www.merriam-webster.com/dictionary/dutch%20pink) don't have to be capitalized.  Ah, English.

I believe that if one were to get in the weeds, CMOS (Chicago Manual of Style, not the BIOS) would be the most appropriate style guide to standardize on, but I don't happen to have the book or the subscription.  In my latest pull request, I started documenting the types of corrections I am most commonly making, so that everyone can see a bit of the style guide that's in my head.

**Comment by hendricius** [comment]
@hanclintonnyx sorry to hijkack this old PR. We are currently considering to change the license of the book to something more suitable for an open source book. Would you be okay with the change? You can read a bit more here: https://github.com/hendricius/the-sourdough-framework/pull/177. I'd just need your okay over there ideally. Thank you!!!

**Pull request merged**
