### PR TITLE
Typo in readme

### PR DESCRIPTION
**Pull request by cedounet**
just typos

### CODE REVIEW

**Comment by hendricius** [comment]
Thanks, good catch! LGTM - seems like there are some conflicts with the previous PR? Could you have a look and resolve them please? Then I can merge the PR 👍

**Comment by hendricius** [comment]
@cedounet this is strange? It still shows a lot of changes to the makefile, was that done on purpose?

**Comment by cedounet** [comment]
@hendricius  nope not sure what happened when i clicked.. I will have a look now.

**Comment by cedounet** [comment]
Not sure how i manage to hang myself on this one.  It is a single commit so simpler i create a new branch,

**Pull request closed without merging**
