### PR TITLE
Fix misspellings

### PR DESCRIPTION
**Pull request by szepeviktor**
Hunspell found a few ...

There are many US spellings 😢 not fixed in this PR.

Related to #374

### CODE REVIEW

**Comment by szepeviktor** [comment]
I am confused #62 US spellchecking produces **more** results.

**Comment by hendricius** [comment]
Thanks @szepeviktor. Let's agree on that we use US spelling looking forward. I saw some changes in this PR to British english. Also like your idea of an automated spell checker.

**Comment by szepeviktor** [comment]
@hendricius Done 🍏 

This is my command for Hunspell
```
cat $(git ls-files '*.tex')|sed 's/\\[a-z{}]\+/ /g'|../hunspell-en_US|sort -f|uniq -i|grep -v '^[0-9]'
```
`sed` is not a great tex parser!

**Comment by szepeviktor** [comment]
pandoc is better at it
```
git ls-files '*.tex' -- ':!:book/figures/vars.tex'|xargs -n 1 -- pandoc --to=plain --wrap=none|../hunspell-en_US|sort -f|uniq -i
```

**Comment by hendricius** [comment]
Thanks!

**Comment by szepeviktor** [comment]
Glad to contribute.

**Pull request merged**
