### PR TITLE
Bacteria section

### PR DESCRIPTION
**Pull request by crankycyclops**
Hi Hendrik,

I've just finished (mostly) editing the bacteria section of the "How Sourdough Works" chapter. I did have one question for you about my edits, which I left as a latex comment in the code. Please take a look and let me know how you'd like me to address that last paragraph. I've finished the rest of the section.

### CODE REVIEW

**Comment by hendricius** [comment]
Thank you, great edits! Appreciate it a lot!

I have read the described points from your comments before. However I have not found a scientific source that confirms this yet. I have also been testing this on my own and could not validate it. Maybe we could add this as a point and then say that more research is needed?

```
Some sources describe that fermentation at a low temperature increases acetic acid production, while warmer temperature could boost lactic acid production. In my own tests I could not verify this. More research is needed on the topic.

```

**Comment by crankycyclops** [comment]
> ```
> Some sources describe that fermentation at a low temperature increases acetic acid production, while warmer temperature could boost lactic acid production. In my own tests I could not verify this. More research is needed on the topic.
> ```

I like that. I'll add this and update the PR. Thanks!

**Comment by crankycyclops** [comment]
Alright, I've finished the section :)

**Comment by hendricius** [comment]
Thank you 🚀

**Pull request merged**
