### PR TITLE
Fix duplicate flowchart

### PR DESCRIPTION
**Pull request by hendricius**
This combines both flowcharts into one

### CODE REVIEW

**Review by cedounet — CHANGES_REQUESTED** [review]
Thanks @hendricius 
I will fix the flowcharts (but not today)

- Start on pink
- Use right angles between states.
-  Boxes same size-ish if i can

To make sure I get this right 

4 Options in the path:
48h: 1/10/10, 6-12h 1/10/10, prepare dough
48h: 1/10/10, 6-12h 1/10/10, extend another 6/12 h with 1/5/5 prepare dough

6-12h: 1/5/5, prepare dough
6-12h: 1/5/5,0 , extend another 6/12 h with 1/5/5 prepare dough

Do not hate me please 😸

**Comment by hendricius** [comment]
Thanks for the great feedback! That sounds good. Looking forward to seeing your magic.

**Comment by cedounet** [comment]
What about ?

Screenshot 2023-09-09 at 18 10 40

**Comment by hendricius** [comment]
Lovely. They are so good they could be used directly in the printed book
😅. The designer is currently remaking them in a similar fashion manually.

**Comment by cedounet** [comment]
or 
Screenshot 2023-09-09 at 18 26 25

**Comment by cedounet** [comment]
> Lovely. They are so good they could be used directly in the printed book 

Nope, the book is actual art.. here all i do is aligning stuff to make them look clean.

**Comment by hendricius** [comment]
I prefer #1. It's a bit more aligned 😎

**Comment by cedounet** [comment]
I don't.. surprise...

image

**Comment by hendricius** [comment]
😂 your call then 👍

**Comment by cedounet** [comment]
Made several commits, so you can cherry-pick what you like and what you don't.  😎

**Review by cedounet — APPROVED** [review]

**Comment by hendricius** [comment]
No worries. Thank you for the great changes!

**Pull request merged**
